package com.grephq.ot.obd.Encoded;

/**
 * Fuel type of vehicle
 */
public enum FuelType {
    NOT_AVAILABLE,
    GASOLINE,
    METHANOL,
    ETHANOL,
    DIESEL,
    LPG,
    CNG,
    PROPANE,
    ELECTRIC,
    BIFUEL_RUNNING_GASOLINE,
    BIFUEL_RUNNING_METHANOL,
    BIFUEL_RUNNING_ETHANOL,
    BIFUEL_RUNNING_LPG,
    BIFUEL_RUNNING_CNG,
    BIFUEL_RUNNING_PROPANE,
    BIFUEL_RUNNING_ELECTRICITY,
    BIFUEL_RUNNING_ELECTRIC_AND_COMBUSTION_ENGINE,
    HYBRID_GASOLINE,
    HYBRID_ETHANOL,
    HYBRID_DIESEL,
    HYBRID_ELECTRIC,
    HYBRID_RUNNING_ELECTRIC_AND_COMBUSTION_ENGINE,
    HYBRID_REGENERATIVE,
    BIFUEL_RUNNING_DIESEL
}
