package com.grephq.ot.obd.Encoded;

import java.util.HashMap;
import java.util.Map;

/**
 * OBD-II Diagnostic Trouble Codes
 * The first letter denotes what part of the car is at fault.
 * P = Powertrain
 * B = Body
 * C = Chassis
 * U = Network
 *
 * The first of the four numbers will be either a ‘0’ or a ‘1’.
 * 0 = Standardized (SAE) fault codes
 * 1 = Manufacturer specific codes
 *
 * The second digit denotes which of the car systems is at fault. There are eight different categories;
 * 0 = Fuel and Air Metering and Auxiliary Emission Controls
 * 1 = Fuel and Air Metering
 * 2 = Fuel and Air Metering (injector circuit)
 * 3 = Ignition systems or misfires
 * 4 = Auxiliary emission controls
 * 5 = Vehicle speed control & idle control systems
 * 6 = Computer & output circuit
 * 7 = Transmission
 *
 * The third and fourth digits are simply used to define the exact fault code in question.
 */
public class TroubleCode {

    /**
     * Powertrain trouble codes
     */
    public static final Map<String, String> P = new HashMap<String, String>() {{
        put("P0000", "No fault");

        // DTC Codes - P0100-P0199 – Fuel and Air Metering
        put("P0100", "Mass or Volume Air Flow Circuit Malfunction");
        put("P0101", "Mass or Volume Air Flow Circuit Range/Performance");
        put("P0102", "Mass or Volume Air Flow Circuit Low Input");
        put("P0103", "Mass or Volume Air Flow Circuit High Input");
        put("P0104", "Mass or Volume Air Flow Circuit Intermittent");
        put("P0105", "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction");
        put("P0106", "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem");
        put("P0107", "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input");
        put("P0108", "Manifold Absolute Pressure/Barometric Pressure Circuit High Input");
        put("P0109", "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent");
        put("P0110", "Intake Air Temperature Circuit Malfunction");
        put("P0111", "Intake Air Temperature Circuit Range/Performance Problem");
        put("P0112", "Intake Air Temperature Circuit Low Input");
        put("P0113", "Intake Air Temperature Circuit High Input");
        put("P0114", "Intake Air Temperature Circuit Intermittent");
        put("P0115", "Engine Coolant Temperature Circuit Malfunction");
        put("P0116", "Engine Coolant Temperature Circuit Range/Performance Problem");
        put("P0117", "Engine Coolant Temperature Circuit Low Input");
        put("P0118", "Engine Coolant Temperature Circuit High Input");
        put("P0119", "Engine Coolant Temperature Circuit Intermittent");
        put("P0120", "Throttle/Petal Position Sensor/Switch A Circuit Malfunction");
        put("P0121", "Throttle/Petal Position Sensor/Switch A Circuit Range/Performance Problem");
        put("P0122", "Throttle/Petal Position Sensor/Switch A Circuit Low Input");
        put("P0123", "Throttle/Petal Position Sensor/Switch A Circuit High Input");
        put("P0124", "Throttle/Petal Position Sensor/Switch A Circuit Intermittent");
        put("P0125", "Insufficient Coolant Temperature for Closed Loop Fuel Control");
        put("P0126", "Insufficient Coolant Temperature for Stable Operation");
        put("P0127", "Intake Air Temperature Too High");
        put("P0128", "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)");
        put("P0129", "Barometric Pressure Too Low");
        put("P0130", "02 Sensor Circuit Malfunction (Bank I Sensor 1)");
        put("P0131", "02 Sensor Circuit Low Voltage (Bank I Sensor I)");
        put("P0132", "02 Sensor Circuit High Voltage (Bank I Sensor 1)");
        put("P0133", "02 Sensor Circuit Slow Response (Bank 1 Sensor 1)");
        put("P0134", "02 Sensor Circuit No Activity Detected (Bank I Sensor 1)");
        put("P0135", "02 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)");
        put("P0136", "02 Sensor Circuit Malfunction (Bank I Sensor 2)");
        put("P0137", "02 Sensor Circuit Low Voltage (Bank I Sensor 2)");
        put("P0138", "02 Sensor Circuit High Voltage (Bank I Sensor 2)");
        put("P0139", "02 Sensor Circuit Slow Response (Bank 1 Sensor 2)");
        put("P0140", "02 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)");
        put("P0141", "02 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)");
        put("P0142", "02 Sensor Circuit Malfunction (Bank I Sensor 3)");
        put("P0143", "02 Sensor Circuit Low Voltage (Bank I Sensor 3)");
        put("P0144", "02 Sensor Circuit High Voltage (Bank I Sensor 3)");
        put("P0145", "02 Sensor Circuit Slow Response (Bank 1 Sensor 3)");
        put("P0146", "02 Sensor Circuit No Activity Detected (Bank I Sensor 3)");
        put("P0147", "02 Sensor Heater Circuit Malfunction (Bank I Sensor 3)");
        put("P0148 Fuel", "Delivery Error");
        put("P0149 Fuel", "Timing Error");
        put("P0150", "02 Sensor Circuit Malfunction (Bank 2 Sensor I)");
        put("P0151", "02 Sensor Circuit Low Voltage (Bank 2 Sensor I)");
        put("P0152", "02 Sensor Circuit High Voltage (Bank 2 Sensor 1)");
        put("P0153", "02 Sensor Circuit Slow Response (Bank 2 Sensor 1)");
        put("P0154", "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)");
        put("P0155", "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)");
        put("P0156", "02 Sensor Circuit Malfunction (Bank 2 Sensor 2)");
        put("P0157", "02 Sensor Circuit Low Voltage (Bank 2 Sensor 2)");
        put("P0158", "02 Sensor Circuit High Voltage (Bank 2 Sensor 2)");
        put("P0159", "02 Sensor Circuit Slow Response (Bank 2 Sensor 2)");
        put("P0160", "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)");
        put("P0161", "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)");
        put("P0162", "02 Sensor Circuit Malfunction (Bank 2 Sensor 3)");
        put("P0163", "02 Sensor Circuit Low Voltage (Bank 2 Sensor 3)");
        put("P0164", "02 Sensor Circuit High Voltage (Bank 2 Sensor 3)");
        put("P0165", "02 Sensor Circuit Slow Response (Bank 2 Sensor 3)");
        put("P0166", "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 3)");
        put("P0167", "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 3)");
        put("P0168", "Fuel Temperature Too High");
        put("P0169", "Incorrect Fuel Composition");
        put("P0170", "Fuel Trim Malfunction (Bank 1)");
        put("P0171", "System too Lean (Bank 1)");
        put("P0172", "System too Rich (Bank 1)");
        put("P0173", "Fuel Trim Malfunction (Bank 2)");
        put("P0174", "System too Lean (Bank 2)");
        put("P0175", "System too Rich (Bank 2)");
        put("P0176", "Fuel Composition Sensor Circuit Malfunction");
        put("P0177", "Fuel Composition Sensor Circuit Range/Performance");
        put("P0178", "Fuel Composition Sensor Circuit Low Input");
        put("P0179", "Fuel Composition Sensor Circuit High Input");
        put("P0180", "Fuel Temperature Sensor A Circuit Malfunction");
        put("P0181", "Fuel Temperature Sensor A Circuit Range/Performance");
        put("P0182", "Fuel Temperature Sensor A Circuit Low Input");
        put("P0183", "Fuel Temperature Sensor A Circuit High Input");
        put("P0184", "Fuel Temperature Sensor A Circuit Intermittent");
        put("P0185", "Fuel Temperature Sensor B Circuit Malfunction");
        put("P0186", "Fuel Temperature Sensor B Circuit Range/Performance");
        put("P0187", "Fuel Temperature Sensor B Circuit Low Input");
        put("P0188", "Fuel Temperature Sensor B Circuit High Input");
        put("P0189", "Fuel Temperature Sensor B Circuit Intermittent");
        put("P0190", "Fuel Rail Pressure Sensor Circuit Malfunction");
        put("P0191", "Fuel Rail Pressure Sensor Circuit Range/Performance");
        put("P0192", "Fuel Rail Pressure Sensor Circuit Low Input");
        put("P0193", "Fuel Rail Pressure Sensor Circuit High Input");
        put("P0194", "Fuel Rail Pressure Sensor Circuit Intermittent");
        put("P0195", "Engine Oil Temperature Sensor Malfunction");
        put("P0196", "Engine Oil Temperature Sensor Range/Performance");
        put("P0197", "Engine Oil Temperature Sensor Low");
        put("P0198", "Engine Oil Temperature Sensor High");
        put("P0199", "Engine Oil Temperature Sensor Intermittent");

        // DTC Codes - P0200-P0299 – Fuel and Air Metering (Injector Circuit)
        put("P0200", "Injector Circuit Malfunction");
        put("P0201", "Injector Circuit Malfunction - Cylinder 1");
        put("P0202", "Injector Circuit Malfunction - Cylinder 2");
        put("P0203", "Injector Circuit Malfunction - Cylinder 3");
        put("P0204", "Injector Circuit Malfunction - Cylinder 4");
        put("P0205", "Injector Circuit Malfunction - Cylinder 5");
        put("P0206", "Injector Circuit Malfunction - Cylinder 6");
        put("P0207", "Injector Circuit Malfunction - Cylinder 7");
        put("P0208", "Injector Circuit Malfunction - Cylinder 8");
        put("P0209", "Injector Circuit Malfunction - Cylinder 9");
        put("P0210", "Injector Circuit Malfunction - Cylinder 10");
        put("P0211", "Injector Circuit Malfunction - Cylinder 11");
        put("P0212", "Injector Circuit Malfunction - Cylinder 12");
        put("P0213", "Cold Start Injector 1 Malfunction");
        put("P0214", "Cold Start Injector 2 Malfunction");
        put("P0215", "Engine Shutoff Solenoid Malfunction");
        put("P0216", "Injection Timing Control Circuit Malfunction");
        put("P0217", "Engine Overtemp Condition");
        put("P0218", "Transmission Over Temperature Condition");
        put("P0219", "Engine Overspeed Condition");
        put("P0220", "Throttle/Petal Position Sensor/Switch B Circuit Malfunction");
        put("P0221", "Throttle/Petal Position Sensor/Switch B Circuit Range/Performance Problem");
        put("P0222", "Throttle/Petal Position Sensor/Switch B Circuit Low Input");
        put("P0223", "Throttle/Petal Position Sensor/Switch B Circuit High Input");
        put("P0224", "Throttle/Petal Position Sensor/Switch B Circuit Intermittent");
        put("P0225", "Throttle/Petal Position Sensor/Switch C Circuit Malfunction");
        put("P0226", "Throttle/Petal Position Sensor/Switch C Circuit Range/Performance Problem");
        put("P0227", "Throttle/Petal Position Sensor/Switch C Circuit Low Input");
        put("P0228", "Throttle/Petal Position Sensor/Switch C Circuit High Input");
        put("P0229", "Throttle/Petal Position Sensor/Switch C Circuit Intermittent");
        put("P0230", "Fuel Pump Primary Circuit Malfunction");
        put("P0231", "Fuel Pump Secondary Circuit Low");
        put("P0232", "Fuel Pump Secondary Circuit High");
        put("P0233", "Fuel Pump Secondary Circuit Intermittent");
        put("P0234", "Engine Overboost Condition");
        put("P0235", "Turbocharger Boost Sensor A Circuit Malfunction");
        put("P0236", "Turbocharger Boost Sensor A Circuit Range/Performance");
        put("P0237", "Turbocharger Boost Sensor A Circuit Low");
        put("P0238", "Turbocharger Boost Sensor A Circuit High");
        put("P0239", "Turbocharger Boost Sensor B Malfunction");
        put("P0240", "Turbocharger Boost Sensor B Circuit Range/Performance");
        put("P0241", "Turbocharger Boost Sensor B Circuit Low");
        put("P0242", "Turbocharger Boost Sensor B Circuit High");
        put("P0243", "Turbocharger Wastegate Solenoid A Malfunction");
        put("P0244", "Turbocharger Wastegate Solenoid A Range/Performance");
        put("P0245", "Turbocharger Wastegate Solenoid A Low");
        put("P0246", "Turbocharger Wastegate Solenoid A High");
        put("P0247", "Turbocharger Wastegate Solenoid B Malfunction");
        put("P0248", "Turbocharger Wastegate Solenoid B Range/Performance");
        put("P0249", "Turbocharger Wastegate Solenoid B Low");
        put("P0250", "Turbocharger Wastegate Solenoid B High");
        put("P0251", "Injection Pump Fuel Metering Control \"A\" Malfunction (Cam/Rotor/Injector)");
        put("P0252", "Injection Pump Fuel Metering Control \"A\" Range/Performance (Cam/Rotor/Injector)");
        put("P0253", "Injection Pump Fuel Metering Control \"A\" Low (Cam/Rotor/Injector)");
        put("P0254", "Injection Pump Fuel Metering Control \"A\" High (Cam/Rotor/Injector)");
        put("P0255", "Injection Pump Fuel Metering Control \"A\" Intermittent (Cam/Rotor/Injector)");
        put("P0256", "Injection Pump Fuel Metering Control \"B\" Malfunction (Cam/Rotor/Injector)");
        put("P0257", "Injection Pump Fuel Metering Control \"B\" Range/Performance Injector)");
        put("P0258", "Injection Pump Fuel Metering Control \"B\" Low (Cam/R");
        put("P0259", "Injection Pump Fuel Metering Control \"B\" High (Cam/R");
        put("P0260", "Injection Pump Fuel Metering Control \"B\" Intermittent Injector)");
        put("P0261", "Cylinder I Injector Circuit Low");
        put("P0262", "Cylinder I Injector Circuit High");
        put("P0263", "Cylinder I Contribution/Balance Fault");
        put("P0264", "Cylinder 2 Injector Circuit Low");
        put("P0265", "Cylinder 2 Injector Circuit High");
        put("P0266", "Cylinder 2 Contribution/Balance Fault");
        put("P0267", "Cylinder 3 Injector Circuit Low");
        put("P0268", "Cylinder 3 Injector Circuit High");
        put("P0269", "Cylinder 3 Contribution/Balance Fault");
        put("P0270", "Cylinder 4 Injector Circuit Low");
        put("P0271", "Cylinder 4 Injector Circuit High");
        put("P0272", "Cylinder 4 Contribution/Balance Fault");
        put("P0273", "Cylinder 5 Injector Circuit Low");
        put("P0274", "Cylinder 5 Injector Circuit High");
        put("P0275", "Cylinder S Contribution/Balance Fault");
        put("P0276", "Cylinder 6 Injector Circuit Low");
        put("P0277", "Cylinder 6 Injector Circuit High");
        put("P0278", "Cylinder 6 Contribution/Balance Fault");
        put("P0279", "Cylinder 7 Injector Circuit Low");
        put("P0280", "Cylinder 7 Injector Circuit High");
        put("P0281", "Cylinder 7 Contribution/Balance Fault");
        put("P0282", "Cylinder 8 Injector Circuit Low");
        put("P0283", "Cylinder 8 Injector Circuit High");
        put("P0284", "Cylinder 8 Contribution/Balance Fault");
        put("P0285", "Cylinder 9 Injector Circuit Low");
        put("P0286", "Cylinder 9 Injector Circuit High");
        put("P0287", "Cylinder 9 Contribution/Balance Fault");
        put("P0288", "Cylinder 10 Injector Circuit Low");
        put("P0289", "Cylinder 10 Injector Circuit High");
        put("P0290", "Cylinder 10 Contribution/Balance Fault");
        put("P0291", "Cylinder 11 Injector Circuit Low");
        put("P0292", "Cylinder 11 Injector Circuit High");
        put("P0293", "Cylinder 11 Contribution/Balance Fault");
        put("P0294", "Cylinder 12 Injector Circuit Low");
        put("P0295", "Cylinder 12 Injector Circuit High");
        put("P0296", "Cylinder 12 Contribution/Range Fault");
        put("P0297", "Vehicle Overspeed Condition");
        put("P0298", "Engine Oil Over Temperature");
        put("P0299", "Turbo/Super Charger Underboost");

        // DTC Codes - P0300-P0399 – Ignition System or Misfire
        put("P0300", "Random/Multiple Cylinder Misfire Detected");
        put("P0301", "Cylinder 1 Misfire Detected");
        put("P0302", "Cylinder 2 Misfire Detected");
        put("P0303", "Cylinder 3 Misfire Detected");
        put("P0304", "Cylinder 4 Misfire Detected");
        put("P0305", "Cylinder 5 Misfire Detected");
        put("P0306", "Cylinder 6 Misfire Detected");
        put("P0307", "Cylinder 7 Misfire Detected");
        put("P0308", "Cylinder 8 Misfire Detected");
        put("P0309", "Cylinder 9 Misfire Detected");
        put("P0310", "Cylinder 10 Misfire Detected");
        put("P0311", "Cylinder 11 Misfire Detected");
        put("P0312", "Cylinder 12 Misfire Detected");
        put("P0313", "Misfire Detected with Low Fuel");
        put("P0314", "Single Cylinder Misfire (Cylinder not Specified)");
        put("P0315", "Crankshaft Position System Variation Not Learned");
        put("P0316", "Engine Misfire Detected on Startup (First 1000 Revolutions)");
        put("P0317", "Rough Road Hardware Not Present");
        put("P0318", "Rough Road Sensor \"A\" Signal Circuit");
        put("P0319", "Rough Road Sensor \"B");
        put("P0320", "Ignition/Distributor Engine Speed Input Circuit Malfunction");
        put("P0321", "Ignition/Distributor Engine Speed Input Circuit Range/Performance");
        put("P0322", "Ignition/Distributor Engine Speed Input Circuit No Signal");
        put("P0323", "Ignition/Distributor Engine Speed Input Circuit Intermittent");
        put("P0325", "Knock Sensor 1 Circuit Malfunction (Bank I or Single Sensor)");
        put("P0326", "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)");
        put("P0327", "Knock Sensor 1 Circuit Low Input (Bank I or Single Sensor)");
        put("P0328", "Knock Sensor 1 Circuit High Input (Bank I or Single Sensor)");
        put("P0329", "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)");
        put("P0330", "Knock Sensor 2 Circuit Malfunction (Bank 2)");
        put("P0331", "Knock Sensor 2 Circuit Range/Performance (Bank 2)");
        put("P0332", "Knock Sensor 2 Circuit Low Input (Bank 2)");
        put("P0333", "Knock Sensor 2 Circuit High Input (Bank 2)");
        put("P0334", "Knock Sensor 2 Circuit Intermittent (Bank 2)");
        put("P0335", "Crankshaft Position Sensor A Circuit Malfunction");
        put("P0336", "Crankshaft Position Sensor A Circuit Range/Performance");
        put("P0337", "Crankshaft Position Sensor A Circuit Low Input");
        put("P0338", "Crankshaft Position Sensor A Circuit High Input");
        put("P0339", "Crankshaft Position Sensor A Circuit Intermittent");
        put("P0340", "Camshaft Position Sensor Circuit Malfunction");
        put("P0341", "Camshaft Position Sensor Circuit Range/Performance");
        put("P0342", "Camshaft Position Sensor Circuit Low Input");
        put("P0343", "Camshaft Position Sensor Circuit High Input");
        put("P0344", "Camshaft Position Sensor Circuit Intermittent");
        put("P0345", "Camshaft Position Sensor \"A\" Circuit");
        put("P0346", "Camshaft Position Sensor \"A\" Circuit Range/Performance");
        put("P0347", "Camshaft Position Sensor \"A\" Circuit Low");
        put("P0348", "Camshaft Position Sensor \"A\" Circuit High");
        put("P0349", "Camshaft Position Sensor \"A\" Circuit Intermittent");
        put("P0350", "Ignition Coil Primary/Secondary Circuit Malfunction");
        put("P0351", "Ignition Coil A Primary/Secondary Circuit Malfunction");
        put("P0352", "Ignition Coil B Primary/Secondary Circuit Malfunction");
        put("P0353", "Ignition Coil C Primary/Secondary Circuit Malfunction");
        put("P0354", "Ignition Coil D Primary/Secondary Circuit Malfunction");
        put("P0355", "Ignition Coil E Primary/Secondary Circuit Malfunction");
        put("P0356", "Ignition Coil F Primary/Secondary Circuit Malfunction");
        put("P0357", "Ignition Coil G Primary/Secondary Circuit Malfunction");
        put("P0358", "Ignition Coil H Primary/Secondary Circuit Malfunction");
        put("P0359", "Ignition Coil I Primary/Secondary Circuit Malfunction");
        put("P0360", "Ignition Coil J Primary/Secondary Circuit Malfunction");
        put("P0361", "Ignition Coil K Primary/Secondary Circuit Malfunction");
        put("P0362", "Ignition Coil L Primary/Secondary Circuit Malfunction");
        put("P0363", "Misfire Detected - Fueling Disabled");
        put("P0364", "Reserved");
        put("P0365", "Camshaft Position Sensor \"B\" Circuit");
        put("P0366", "Camshaft Position Sensor \"B\" Circuit Range/Performance");
        put("P0367", "Camshaft Position Sensor \"B\" Circuit Low");
        put("P0368", "Camshaft Position Sensor \"B\" Circuit High");
        put("P0369", "Camshaft Position Sensor \"B\" Circuit Intermittent");
        put("P0370", "Timing Reference High Resolution Signal A Malfunction");
        put("P0371", "Timing Reference High Resolution Signal A Too Many Pulses");
        put("P0372", "Timing Reference High Resolution Signal A Too Few Pulses");
        put("P0373", "Timing Reference High Resolution Signal A Intermittent/Erratic Pulses");
        put("P0374", "Timing Reference High Resolution Signal A No Pulses");
        put("P0375", "Timing Reference High Resolution Signal B Malfunction");
        put("P0376", "Timing Reference High Resolution Signal B Too Many Pulses");
        put("P0377", "Timing Reference High Resolution Signal B Too Few Pulses");
        put("P0378", "Timing Reference High Resolution Signal B Intermittent/Erratic Pulses");
        put("P0379", "Timing Reference High Resolution Signal B No Pulses");
        put("P0380", "Glow Plug/Heater Circuit \"A\" Malfunction");
        put("P0381", "Glow Plug/Heater Indicator Circuit Malfunction");
        put("P0382", "Exhaust Gas Recirculation Flow Malfunction");
        put("P0383", "Reserved by SAE J2012");
        put("P0384", "Reserved by SAE J2012");
        put("P0385", "Crankshaft Position Sensor B Circuit Malfunction");
        put("P0386", "Crankshaft Position Sensor B Circuit Range/Performance");
        put("P0387", "Crankshaft Position Sensor B Circuit Low Input");
        put("P0388", "Crankshaft Position Sensor B Circuit High Input");
        put("P0389", "Crankshaft Position Sensor B Circuit Intermittent");
        put("P0390", "Camshaft Position Sensor \"B\" Circuit");
        put("P0391", "Camshaft Position Sensor \"B\" Circuit Range/Performance");
        put("P0392", "Camshaft Position Sensor \"B\" Circuit Low");
        put("P0393", "Camshaft Position Sensor \"B\" Circuit High");
        put("P0394", "Camshaft Position Sensor \"B\" Circuit Intermittent");

        // DTC Codes - P0400-P0499 – Auxiliary Emissions Controls
        put("P0400", "Exhaust Gas Recirculation Flow Malfunction");
        put("P0401", "Exhaust Gas Recirculation Flow Insufficient Detected");
        put("P0402", "Exhaust Gas Recirculation Flow Excessive Detected");
        put("P0403", "Exhaust Gas Recirculation Circuit Malfunction");
        put("P0404", "Exhaust Gas Recirculation Circuit Range/Performance");
        put("P0405", "Exhaust Gas Recirculation Sensor A Circuit Low");
        put("P0406", "Exhaust Gas Recirculation Sensor A Circuit High");
        put("P0407", "Exhaust Gas Recirculation Sensor B Circuit Low");
        put("P0408", "Exhaust Gas Recirculation Sensor B Circuit High");
        put("P0410", "Secondary Air Injection System Malfunction");
        put("P0411", "Secondary Air Injection System Incorrect Flow Detected");
        put("P0412", "Secondary Air Injection System Switching Valve A Circuit Malfunction");
        put("P0413", "Secondary Air Injection System Switching Valve A Circuit Open");
        put("P0414", "Secondary Air Injection System Switching Valve A Circuit Shorted");
        put("P0415", "Secondary Air Injection System Switching Valve B Circuit Malfunction");
        put("P0416", "Secondary Air Injection System Switching Valve B Circuit Open");
        put("P0417", "Secondary Air Injection System Switching Valve B Circuit Shorted");
        put("P0418", "Secondary Air Injection System Relay ‘A\" Circuit Malfunction");
        put("P0419", "Secondary Air Injection System Relay \"B’ Circuit Malfunction");
        put("P0420", "Catalyst System Efficiency Below Threshold (Bank 1)");
        put("P0421", "Warm Up Catalyst Efficiency Below Threshold (Bank 1)");
        put("P0422", "Main Catalyst Efficiency Below Threshold (Bank 1)");
        put("P0423", "Heated Catalyst Efficiency Below Threshold (Bank 1)");
        put("P0424", "Heated Catalyst Temperature Below Threshold (Bank 1)");
        put("P0425", "Catalyst Temperature Sensor");
        put("P0426", "Catalyst Temperature Sensor Range/Performance");
        put("P0427", "Catalyst Temperature Sensor Low");
        put("P0428", "Catalyst Temperature Sensor High");
        put("P0429", "Catalyst Heater Control Circuit");
        put("P0430", "Catalyst System Efficiency Below Threshold (Bank 2)");
        put("P0431", "Warm Up Catalyst Efficiency Below Threshold (Bank 2)");
        put("P0432", "Main Catalyst Efficiency Below Threshold (Bank 2)");
        put("P0433", "Heated Catalyst Efficiency Below Threshold (Bank 2)");
        put("P0434", "Heated Catalyst Temperature Below Threshold (Bank 2)");
        put("P0435", "Catalyst Temperature Sensor");
        put("P0436", "Catalyst Temperature Sensor Range/Performance");
        put("P0437", "Catalyst Temperature Sensor Low");
        put("P0438", "Catalyst Temperature Sensor High");
        put("P0439", "Catalyst Heater Control Circuit");
        put("P0440", "Evaporative Emission Control System Malfunction");
        put("P0441", "Evaporative Emission Control System Incorrect Purge Flow");
        put("P0442", "Evaporative Emission Control System Leak Detected (small leak)");
        put("P0443", "Evaporative Emission Control System Purge Control Valve Circuit");
        put("P0444", "Evaporative Emission Control System Purge Control Valve Circuit");
        put("P0445", "Evaporative Emission Control System Purge Control Valve Circuit Shorted");
        put("P0446", "Evaporative Emission Control System Vent Control Circuit Malfunction");
        put("P0447", "Evaporative Emission Control System Vent Control Circuit Open");
        put("P0448", "Evaporative Emission Control System Vent Control Circuit Shorted");
        put("P0449", "Evaporative Emission Control System Vent Valve/Solenoid Circuit Malfunction");
        put("P0450", "Evaporative Emission Control System Pressure Sensor Malfunction");
        put("P0451", "Evaporative Emission Control System Pressure Sensor Range/Performance");
        put("P0452", "Evaporative Emission Control System Pressure Sensor Low Input");
        put("P0453", "Evaporative Emission Control System Pressure Sensor High Input");
        put("P0454", "Evaporative Emission Control System Pressure Sensor Intermittent");
        put("P0455", "Evaporative Emission Control System Leak Detected (gross leak)");
        put("P0456", "Evaporative Emission System Leak Detected (very small leak)");
        put("P0457", "Evaporative Emission System Leak Detected (fuel cap loose/off)");
        put("P0458", "Evaporative Emission System Purge Control Valve Circuit Low");
        put("P0459", "Evaporative Emission System Purge Control Valve Circuit High");
        put("P0460", "Fuel Level Sensor Circuit Malfunction");
        put("P0461", "Fuel Level Sensor Circuit Range/Performance");
        put("P0462", "Fuel Level Sensor Circuit Low Input");
        put("P0463", "Fuel Level Sensor Circuit High Input");
        put("P0464", "Fuel Level Sensor Circuit Intermittent");
        put("P0465", "Purge Flow Sensor Circuit Malfunction");
        put("P0466", "Purge Flow Sensor Circuit Range/Performance");
        put("P0467", "Purge Flow Sensor Circuit Low Input");
        put("P0468", "Purge Flow Sensor Circuit High Input");
        put("P0469", "Purge Flow Sensor Circuit Intermittent");
        put("P0470", "Exhaust Pressure Sensor Malfunction");
        put("P0471", "Exhaust Pressure Sensor Range/Performance");
        put("P0472", "Exhaust Pressure Sensor Low");
        put("P0473", "Exhaust Pressure Sensor High");
        put("P0474", "Exhaust Pressure Sensor Intermittent");
        put("P0475", "Exhaust Pressure Control Valve Malfunction");
        put("P0476", "Exhaust Pressure Control Valve Range/Performance");
        put("P0477", "Exhaust Pressure Control Valve Low");
        put("P0478", "Exhaust Pressure Control Valve High");
        put("P0479", "Exhaust Pressure Control Valve Intermittent");
        put("P0480", "Cooling Fan I Control Circuit Malfunction");
        put("P0481", "Cooling Fan 2 Control Circuit Malfunction");
        put("P0482", "Cooling Fan 3 Control Circuit Malfunction");
        put("P0483", "Cooling Fan Rationality Check Malfunction");
        put("P0484", "Cooling Fan Circuit Over Current");
        put("P0485", "Cooling Fan Power/Ground Circuit Malfunction");
        put("P0486", "Exhaust Gas Recirculation Sensor \"B\" Circuit");
        put("P0487", "Exhaust Gas Recirculation Throttle Position Control Circuit");
        put("P0488", "Exhaust Gas Recirculation Throttle Position Control Range/Performance");
        put("P0489", "Exhaust Gas Recirculation Control Circuit Low");
        put("P0490", "Exhaust Gas Recirculation Control Circuit High");
        put("P0491", "Secondary Air Injection System Insufficient Flow");
        put("P0492", "Secondary Air Injection System Insufficient Flow");
        put("P0493", "Fan Overspeed");
        put("P0494", "Fan Speed Low");
        put("P0495", "Fan Speed High");
        put("P0496", "Evaporative Emission System High Purge Flow");
        put("P0497", "Evaporative Emission System Low Purge Flow");
        put("P0498", "Evaporative Emission System Vent Valve Control Circuit Low");
        put("P0499", "Evaporative Emission System Vent Valve Control Circuit High");

        // DTC Codes - P0500-P0599 – Vehicle Speed Controls and Idle Control System
        put("P0500", "Vehicle Speed Sensor Malfunction");
        put("P0501", "Vehicle Speed Sensor Range/Performance");
        put("P0502", "Vehicle Speed Sensor Low Input");
        put("P0503", "Vehicle Speed Sensor Intermittent/Erratic/High");
        put("P0504", "Brake Switch \"A\"/\"B\" Correlation");
        put("P0505", "Idle Control System Malfunction");
        put("P0506", "Idle Control System RPM Lower Than Expected");
        put("P0507", "Idle Control System RPM Higher Than Expected");
        put("P0508", "Idle Air Control System Circuit Low");
        put("P0509", "Idle Air Control System Circuit High");
        put("P0510", "Closed Throttle Position Switch Malfunction");
        put("P0511", "Idle Air Control Circuit");
        put("P0512", "Starter Request Circuit");
        put("P0513", "Incorrect Immobilizer Key");
        put("P0514", "Battery Temperature Sensor Circuit Range/Performance");
        put("P0515", "Battery Temperature Sensor Circuit");
        put("P0516", "Battery Temperature Sensor Circuit Low");
        put("P0517", "Battery Temperature Sensor Circuit High");
        put("P0518", "Idle Air Control Circuit Intermittent");
        put("P0519", "Idle Air Control System Performance");
        put("P0520", "Engine Oil Pressure Sensor/Switch Circuit Malfunction");
        put("P0521", "Engine Oil Pressure Sensor/Switch Circuit Range/Performance");
        put("P0522", "Engine Oil Pressure Sensor/Switch Circuit Low Voltage");
        put("P0523", "Engine Oil Pressure Sensor/Switch Circuit High Voltage");
        put("P0524", "Engine Oil Pressure Too Low");
        put("P0525", "Cruise Control Servo Control Circuit Range/Performance");
        put("P0526", "Fan Speed Sensor Circuit");
        put("P0527", "Fan Speed Sensor Circuit Range/Performance");
        put("P0528", "Fan Speed Sensor Circuit No Signal");
        put("P0529", "Fan Speed Sensor Circuit Intermittent");
        put("P0530", "A/C Refrigerant Pressure Sensor Circuit Malfunction");
        put("P0531", "A/C Refrigerant Pressure Sensor Circuit Range/Performance");
        put("P0532", "A/C Refrigerant Pressure Sensor Circuit Low Input");
        put("P0533", "A/C Refrigerant Pressure Sensor Circuit High Input");
        put("P0534", "Air Conditioner Refrigerant Charge Loss");
        put("P0535", "A/C Evaporator Temperature Sensor Circuit");
        put("P0536", "A/C Evaporator Temperature Sensor Circuit Range/Performance");
        put("P0537", "A/C Evaporator Temperature Sensor Circuit Low");
        put("P0538", "A/C Evaporator Temperature Sensor Circuit High");
        put("P0539", "A/C Evaporator Temperature Sensor Circuit Intermittent");
        put("P0540", "Intake Air Heater \"A\" Circuit");
        put("P0541", "Intake Air Heater \"A\" Circuit Low");
        put("P0542", "Intake Air Heater \"A\" Circuit High");
        put("P0543", "Intake Air Heater \"A\" Circuit Open");
        put("P0544", "Exhaust Gas Temperature Sensor Circuit");
        put("P0545", "Exhaust Gas Temperature Sensor Circuit Low");
        put("P0546", "Exhaust Gas Temperature Sensor Circuit High");
        put("P0547", "Exhaust Gas Temperature Sensor Circuit");
        put("P0548", "Exhaust Gas Temperature Sensor Circuit Low");
        put("P0549", "Exhaust Gas Temperature Sensor Circuit High");
        put("P0550", "Power Steering Pressure Sensor Circuit Malfunction");
        put("P0551", "Power Steering Pressure Sensor Circuit Range/Performance");
        put("P0552", "Power Steering Pressure Sensor Circuit Low Input");
        put("P0553", "Power Steering Pressure Sensor Circuit High Input");
        put("P0554", "Power Steering Pressure Sensor Circuit Intermittent");
        put("P0555", "Brake Booster Pressure Sensor Circuit");
        put("P0556", "Brake Booster Pressure Sensor Circuit Range/Performance");
        put("P0557", "Brake Booster Pressure Sensor Circuit Low Input");
        put("P0558", "Brake Booster Pressure Sensor Circuit High Input");
        put("P0559", "Brake Booster Pressure Sensor Circuit Intermittent");
        put("P0560", "System Voltage Malfunction");
        put("P0561", "System Voltage Unstable");
        put("P0562", "System Voltage Low");
        put("P0563", "System Voltage High");
        put("P0565", "Cruise Control On Signal Malfunction");
        put("P0566", "Cruise Control Off Signal Malfunction");
        put("P0567", "Cruise Control Resume Signal Malfunction");
        put("P0568", "Cruise Control Set Signal Malfunction");
        put("P0569", "Cruise Control Coast Signal Malfunction");
        put("P0570", "Cruise Control Accel Signal Malfunction");
        put("P0571", "Cruise Control/Brake Switch A Circuit Malfunction");
        put("P0572", "Cruise Control/Brake Switch A Circuit Low");
        put("P0573", "Cruise Control/Brake Switch A Circuit High");
        put("P0574", "Cruise Control Related Malfunction");
        put("P0575", "Cruise Control Related Malfunction");
        put("P0576", "Cruise Control Related Malfunction");
        put("P0577", "Cruise Control Related Malfunction");
        put("P0578", "Cruise Control Related Malfunction");
        put("P0579", "Cruise Control Related Malfunction");
        put("P0580", "Cruise Control Related Malfunction");
        put("P0581", "Cruise Control Multi-Function Input \"A\" Circuit High");
        put("P0582", "Cruise Control Vacuum Control Circuit/Open");
        put("P0583", "Cruise Control Vacuum Control Circuit Low");
        put("P0584", "Cruise Control Vacuum Control Circuit High");
        put("P0585", "Cruise Control Multi-Function Input \"A\"/\"B\" Correlation");
        put("P0586", "Cruise Control Vent Control Circuit/Open");
        put("P0587", "Cruise Control Vent Control Circuit Low");
        put("P0588", "Cruise Control Vent Control Circuit High");
        put("P0589", "Cruise Control Multi-Function Input \"B\" Circuit");
        put("P0590", "Cruise Control Multi-Function Input \"B\" Circuit Stuck");
        put("P0591", "Cruise Control Multi-Function Input \"B\" Circuit Range/Performance");
        put("P0592", "Cruise Control Multi-Function Input \"B\" Circuit Low");
        put("P0593", "Cruise Control Multi-Function Input \"B\" Circuit High");
        put("P0594", "Cruise Control Servo Control Circuit/Open");
        put("P0595", "Cruise Control Servo Control Circuit Low");
        put("P0596", "Cruise Control Servo Control Circuit High");
        put("P0597", "Thermostat Heater Control Circuit/Open");
        put("P0598", "Thermostat Heater Control Circuit Low");
        put("P0599", "Thermostat Heater Control Circuit High");

        // DTC Codes - P0600-P0699 – Computer Output Circuit
        put("P0600", "Serial Communication Link Malfunction");
        put("P0601", "Internal Control Module Memory Check Sum Error");
        put("P0602", "Control Module Programming Error");
        put("P0603", "Internal Control Module Keep Alive Memory (KAM) Error");
        put("P0604", "Internal Control Module Random Access Memory (RAM) Error");
        put("P0605", "Internal Control Module Read Only Memory (ROM) Error");
        put("P0606", "PCM Processor Fault");
        put("P0608", "Control Module VSS Output \"A’ Malfunction");
        put("P0609", "Control Module VSS Output \"B\" Malfunction");
        put("P0610", "Control Module Vehicle Options Error");
        put("P0611", "Fuel Injector Control Module Performance");
        put("P0612", "Fuel Injector Control Module Relay Control");
        put("P0613", "TCM Processor");
        put("P0614", "ECM / TCM Incompatible");
        put("P0615", "Starter Relay Circuit");
        put("P0616", "Starter Relay Circuit Low");
        put("P0617", "Starter Relay Circuit High");
        put("P0618", "Alternative Fuel Control Module KAM Error");
        put("P0619", "Alternative Fuel Control Module RAM/ROM Error");
        put("P0620", "Generator Control Circuit Malfunction");
        put("P0621", "Generator Lamp \"L\" Control Circuit Malfunction");
        put("P0622", "Generator Field \"F\" Control Circuit Malfunction");
        put("P0623", "Generator Lamp Control Circuit");
        put("P0624", "Fuel Cap Lamp Control Circuit");
        put("P0625", "Generator Field/F Terminal Circuit Low");
        put("P0626", "Generator Field/F Terminal Circuit High");
        put("P0627", "Fuel Pump \"A\" Control Circuit /Open");
        put("P0628", "Fuel Pump \"A\" Control Circuit Low");
        put("P0629", "Fuel Pump \"A\" Control Circuit High");
        put("P0630", "VIN Not Programmed or Incompatible - ECM/PCM");
        put("P0631", "VIN Not Programmed or Incompatible - TCM");
        put("P0632", "Odometer Not Programmed - ECM/PCM");
        put("P0633", "Immobilizer Key Not Programmed - ECM/PCM");
        put("P0634", "PCM/ECM/TCM Internal Temperature Too High");
        put("P0635", "Power Steering Control Circuit");
        put("P0636", "Power Steering Control Circuit Low");
        put("P0637", "Power Steering Control Circuit High");
        put("P0638", "Throttle Actuator Control Range/Performance");
        put("P0639", "Throttle Actuator Control Range/Performance");
        put("P0640", "Intake Air Heater Control Circuit");
        put("P0641", "Sensor Reference Voltage \"A\" Circuit/Open");
        put("P0642", "Sensor Reference Voltage \"A\" Circuit Low");
        put("P0643", "Sensor Reference Voltage \"A\" Circuit High");
        put("P0644", "Driver Display Serial Communication Circuit");
        put("P0645", "A/C Clutch Relay Control Circuit");
        put("P0646", "A/C Clutch Relay Control Circuit Low");
        put("P0647", "A/C Clutch Relay Control Circuit High");
        put("P0648", "Immobilizer Lamp Control Circuit");
        put("P0649", "Speed Control Lamp Control Circuit");
        put("P0650", "Malfunction Indicator Lamp (MIL) Control Circuit Malfunction");
        put("P0654", "Engine RPM Output Circuit Malfunction");
        put("P0655", "Engine Hot Lamp Output Control Circuit Malfunction");
        put("P0656", "Fuel Level Output Circuit Malfunction");
        put("P0657", "Actuator Supply Voltage \"A\" Circuit/Open");
        put("P0658", "Actuator Supply Voltage \"A\" Circuit Low");
        put("P0659", "Actuator Supply Voltage \"A\" Circuit High");
        put("P0660", "Intake Manifold Tuning Valve Control Circuit/Open");
        put("P0661", "Intake Manifold Tuning Valve Control Circuit Low");
        put("P0662", "Intake Manifold Tuning Valve Control Circuit High");
        put("P0663", "Intake Manifold Tuning Valve Control Circuit/Open");
        put("P0664", "Intake Manifold Tuning Valve Control Circuit Low");
        put("P0665", "Intake Manifold Tuning Valve Control Circuit High");
        put("P0666", "PCM/ECM/TCM Internal Temperature Sensor Circuit");
        put("P0667", "PCM/ECM/TCM Internal Temperature Sensor Range/Performance");
        put("P0668", "PCM/ECM/TCM Internal Temperature Sensor Circuit Low");
        put("P0669", "PCM/ECM/TCM Internal Temperature Sensor Circuit High");
        put("P0670", "Glow Plug Module Control Circuit");
        put("P0671", "Cylinder 1 Glow Plug Circuit");
        put("P0672", "Cylinder 2 Glow Plug Circuit");
        put("P0673", "Cylinder 3 Glow Plug Circuit");
        put("P0674", "Cylinder 4 Glow Plug Circuit");
        put("P0675", "Cylinder 5 Glow Plug Circuit");
        put("P0676", "Cylinder 6 Glow Plug Circuit");
        put("P0677", "Cylinder 7 Glow Plug Circuit");
        put("P0678", "Cylinder 8 Glow Plug Circuit");
        put("P0679", "Cylinder 9 Glow Plug Circuit");
        put("P0680", "Cylinder 10 Glow Plug Circuit");
        put("P0681", "Cylinder 11 Glow Plug Circuit");
        put("P0682", "Cylinder 12 Glow Plug Circuit");
        put("P0683", "Glow Plug Control Module to PCM Communication Circuit");
        put("P0684", "Glow Plug Control Module to PCM Communication Circuit Range/Performance");
        put("P0685", "ECM/PCM Power Relay Control Circuit /Open");
        put("P0686", "ECM/PCM Power Relay Control Circuit Low");
        put("P0687", "ECM/PCM Power Relay Control Circuit High");
        put("P0688", "ECM/PCM Power Relay Sense Circuit /Open");
        put("P0689", "ECM/PCM Power Relay Sense Circuit Low");
        put("P0690", "ECM/PCM Power Relay Sense Circuit High");
        put("P0691", "Fan 1 Control Circuit Low");
        put("P0692", "Fan 1 Control Circuit High");
        put("P0693", "Fan 2 Control Circuit Low");
        put("P0694", "Fan 2 Control Circuit High");
        put("P0695", "Fan 3 Control Circuit Low");
        put("P0696", "Fan 3 Control Circuit High");
        put("P0697", "Sensor Reference Voltage \"C\" Circuit/Open");
        put("P0698", "Sensor Reference Voltage \"C\" Circuit Low");
        put("P0699", "Sensor Reference Voltage \"C\" Circuit High");

        // DTC Codes - P0700-P0899 – Transmission
        put("P0700", "Transmission Control System Malfunction");
        put("P0701", "Transmission Control System Range/Performance");
        put("P0702", "Transmission Control System Electrical");
        put("P0703", "Torque Converter/Brake Switch B Circuit Malfunction");
        put("P0704", "Clutch Switch Input Circuit Malfunction");
        put("P0705", "Transmission Range Sensor Circuit malfunction (PRNDL Input)");
        put("P0706", "Transmission Range Sensor Circuit Range/Performance");
        put("P0707", "Transmission Range Sensor Circuit Low Input");
        put("P0708", "Transmission Range Sensor Circuit High Input");
        put("P0709", "Transmission Range Sensor Circuit Intermittent");
        put("P0710", "Transmission Fluid Temperature Sensor Circuit Malfunction");
        put("P0711", "Transmission Fluid Temperature Sensor Circuit Range/Performance");
        put("P0712", "Transmission Fluid Temperature Sensor Circuit Low Input");
        put("P0713", "Transmission Fluid Temperature Sensor Circuit High Input");
        put("P0714", "Transmission Fluid Temperature Sensor Circuit Intermittent");
        put("P0715", "Input/Turbine Speed Sensor Circuit Malfunction");
        put("P0716", "Input/Turbine Speed Sensor Circuit Range/Performance");
        put("P0717", "Input/Turbine Speed Sensor Circuit No Signal");
        put("P0718", "Input/Turbine Speed Sensor Circuit Intermittent");
        put("P0719", "Torque Converter/Brake Switch B Circuit Low");
        put("P0720", "Output Speed Sensor Circuit Malfunction");
        put("P0721", "Output Speed Sensor Range/Performance");
        put("P0722", "Output Speed Sensor No Signal");
        put("P0723", "Output Speed Sensor Intermittent");
        put("P0724", "Torque Converter/Brake Switch B Circuit High");
        put("P0725", "Engine Speed input Circuit Malfunction");
        put("P0726", "Engine Speed Input Circuit Range/Performance");
        put("P0727", "Engine Speed Input Circuit No Signal");
        put("P0728", "Engine Speed Input Circuit Intermittent");
        put("P0729", "Gear 6 Incorrect Ratio");
        put("P0730", "Incorrect Gear Ratio");
        put("P0731", "Gear I Incorrect ratio");
        put("P0732", "Gear 2 Incorrect ratio");
        put("P0733", "Gear 3 Incorrect ratio");
        put("P0734", "Gear 4 Incorrect ratio");
        put("P0735", "Gear 5 Incorrect ratio");
        put("P0736", "Reverse incorrect gear ratio");
        put("P0737", "TCM Engine Speed Output Circuit");
        put("P0738", "TCM Engine Speed Output Circuit Low");
        put("P0739", "TCM Engine Speed Output Circuit High");
        put("P0740", "Torque Converter Clutch Circuit Malfunction");
        put("P0741", "Torque Converter Clutch Circuit Performance or Stuck Off");
        put("P0742", "Torque Converter Clutch Circuit Stock On");
        put("P0743", "Torque Converter Clutch Circuit Electrical");
        put("P0744", "Torque Converter Clutch Circuit Intermittent");
        put("P0745", "Pressure Control Solenoid Malfunction");
        put("P0746", "Pressure Control Solenoid Performance or Stuck Off");
        put("P0747", "Pressure Control Solenoid Stuck On");
        put("P0748", "Pressure Control Solenoid Electrical");
        put("P0749", "Pressure Control Solenoid Intermittent");
        put("P0750", "Shift Solenoid A Malfunction");
        put("P0751", "Shift Solenoid A Performance or Stuck Off");
        put("P0752", "Shift Solenoid A Stuck On");
        put("P0753", "Shift Solenoid A Electrical");
        put("P0754", "Shift Solenoid A Intermittent");
        put("P0755", "Shift Solenoid B Malfunction");
        put("P0756", "Shift Solenoid B Performance or Stock Off");
        put("P0757", "Shift Solenoid B Stuck On");
        put("P0758", "Shift Solenoid B Electrical");
        put("P0759", "Shift Solenoid B Intermittent");
        put("P0760", "Shift Solenoid C Malfunction");
        put("P0761", "I Shift Solenoid C Performance or Stuck Off");
        put("P0762", "Shift Solenoid C Stuck On");
        put("P0763", "Shift Solenoid C Electrical");
        put("P0764", "Shift Solenoid C Intermittent");
        put("P0765", "Shift Solenoid D Malfunction");
        put("P0766", "Shift Solenoid D Performance or Stuck Off");
        put("P0767", "Shift Solenoid D Stuck On");
        put("P0768", "Shift Solenoid D Electrical");
        put("P0769", "Shift Solenoid D Intermittent");
        put("P0770", "Shift Solenoid E Malfunction");
        put("P0771", "Shift Solenoid E Performance or Stuck Off");
        put("P0772", "Shift Solenoid E Stuck On");
        put("P0773", "Shift Solenoid E Electrical");
        put("P0774", "Shift Solenoid E Intermittent");
        put("P0775", "Pressure Control Solenoid \"B\"");
        put("P0776", "Pressure Control Solenoid \"B\" Performance or Stuck off");
        put("P0777", "Pressure Control Solenoid \"B\" Stuck On");
        put("P0778", "Pressure Control Solenoid \"B\" Electrical");
        put("P0779", "Pressure Control Solenoid \"B\" Intermittent");
        put("P0780", "Shift Malfunction");
        put("P0781", "1-2 Shift Malfunction");
        put("P0782", "2-3 Shift Malfunction");
        put("P0783", "3-4 Shift Malfunction");
        put("P0784", "4-5 Shift Malfunction");
        put("P0785", "Shift/Timing Solenoid Malfunction");
        put("P0786", "Shift/Timing Solenoid Range/Performance");
        put("P0787", "Shift/Timing Solenoid Low");
        put("P0788", "Shift/Timing Solenoid High");
        put("P0789", "Shift/Timing Solenoid Intermittent");
        put("P0790", "Normal/Performance Switch Circuit Malfunction");
        put("P0791", "Intermediate Shaft Speed Sensor \"A\" Circuit");
        put("P0792", "Intermediate Shaft Speed Sensor \"A\" Circuit Range/Performance");
        put("P0793", "Intermediate Shaft Speed Sensor \"A\" Circuit No Signal");
        put("P0794", "Intermediate Shaft Speed Sensor \"A\" Circuit Intermittent");
        put("P0795", "Pressure Control Solenoid \"C\"");
        put("P0796", "Pressure Control Solenoid \"C\" Performance or Stuck off");
        put("P0797", "Pressure Control Solenoid \"C\" Stuck On");
        put("P0798", "Pressure Control Solenoid \"C\" Electrical");
        put("P0799", "Pressure Control Solenoid \"C\" Intermittent");
        put("P0800", "Transfer Case Control System (MIL Request)");
        put("P0801", "Reverse Inhibit Control Circuit Malfunction");
        put("P0803", "1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction");
        put("P0804", "1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction");
        put("P0805", "Clutch Position Sensor Circuit");
        put("P0806", "Clutch Position Sensor Circuit Range/Performance");
        put("P0807", "Clutch Position Sensor Circuit Low");
        put("P0808", "Clutch Position Sensor Circuit High");
        put("P0809", "Clutch Position Sensor Circuit Intermittent");
        put("P0810", "Clutch Position Control Error");
        put("P0811", "Excessive Clutch Slippage");
        put("P0812", "Reverse Input Circuit");
        put("P0813", "Reverse Output Circuit");
        put("P0814", "Transmission Range Display Circuit");
        put("P0815", "Upshift Switch Circuit");
        put("P0816", "Downshift Switch Circuit");
        put("P0817", "Starter Disable Circuit");
        put("P0818", "Driveline Disconnect Switch Input Circuit");
        put("P0819", "Up and Down Shift Switch to Transmission Range Correlation");
        put("P0820", "Gear Lever X-Y Position Sensor Circuit");
        put("P0821", "Gear Lever X Position Circuit");
        put("P0822", "Gear Lever Y Position Circuit");
        put("P0823", "Gear Lever X Position Circuit Intermittent");
        put("P0824", "Gear Lever Y Position Circuit Intermittent");
        put("P0825", "Gear Lever Push-Pull Switch (Shift Anticipate)");
        put("P0826", "Up and Down Shift Switch Circuit");
        put("P0827", "Up and Down Shift Switch Circuit Low");
        put("P0828", "Up and Down Shift Switch Circuit High");
        put("P0829", "5-6 Shift");
        put("P0830", "Clutch Pedal Switch \"A\" Circuit");
        put("P0831", "Clutch Pedal Switch \"A\" Circuit Low");
        put("P0832", "Clutch Pedal Switch \"A\" Circuit High");
        put("P0833", "Clutch Pedal Switch \"B\" Circuit");
        put("P0834", "Clutch Pedal Switch \"B\" Circuit Low");
        put("P0835", "Clutch Pedal Switch \"B\" Circuit High");
        put("P0836", "Four Wheel Drive (4WD) Switch Circuit");
        put("P0837", "Four Wheel Drive (4WD) Switch Circuit Range/Performance");
        put("P0838", "Four Wheel Drive (4WD) Switch Circuit Low");
        put("P0839", "Four Wheel Drive (4WD) Switch Circuit High");
        put("P0840", "Transmission Fluid Pressure Sensor/Switch \"A\" Circuit");
        put("P0841", "Transmission Fluid Pressure Sensor/Switch \"A\" Circuit Range/Performance");
        put("P0842", "Transmission Fluid Pressure Sensor/Switch \"A\" Circuit Low");
        put("P0843", "Transmission Fluid Pressure Sensor/Switch \"A\" Circuit High");
        put("P0844", "Transmission Fluid Pressure Sensor/Switch \"A\" Circuit Intermittent");
        put("P0845", "Transmission Fluid Pressure Sensor/Switch \"B\" Circuit");
        put("P0846", "Transmission Fluid Pressure Sensor/Switch \"B\" Circuit Range/Performance");
        put("P0847", "Transmission Fluid Pressure Sensor/Switch \"B\" Circuit Low");
        put("P0848", "Transmission Fluid Pressure Sensor/Switch \"B\" Circuit High");
        put("P0849", "Transmission Fluid Pressure Sensor/Switch \"B\" Circuit Intermittent");
        put("P0850", "Park/Neutral Switch Input Circuit");
        put("P0851", "Park/Neutral Switch Input Circuit Low");
        put("P0852", "Park/Neutral Switch Input Circuit High");
        put("P0853", "Drive Switch Input Circuit");
        put("P0854", "Drive Switch Input Circuit Low");
        put("P0855", "Drive Switch Input Circuit High");
        put("P0856", "Traction Control Input Signal");
        put("P0857", "Traction Control Input Signal Range/Performance");
        put("P0858", "Traction Control Input Signal Low");
        put("P0859", "Traction Control Input Signal High");
        put("P0860", "Gear Shift Module Communication Circuit");
        put("P0861", "Gear Shift Module Communication Circuit Low");
        put("P0862", "Gear Shift Module Communication Circuit High");
        put("P0863", "TCM Communication Circuit");
        put("P0864", "TCM Communication Circuit Range/Performance");
        put("P0865", "TCM Communication Circuit Low");
        put("P0866", "TCM Communication Circuit High");
        put("P0867", "Transmission Fluid Pressure");
        put("P0868", "Transmission Fluid Pressure Low");
        put("P0869", "Transmission Fluid Pressure High");
        put("P0870", "Transmission Fluid Pressure Sensor/Switch \"C\" Circuit");
        put("P0871", "Transmission Fluid Pressure Sensor/Switch \"C\" Circuit Range/Performance");
        put("P0872", "Transmission Fluid Pressure Sensor/Switch \"C\" Circuit Low");
        put("P0873", "Transmission Fluid Pressure Sensor/Switch \"C\" Circuit High");
        put("P0874", "Transmission Fluid Pressure Sensor/Switch \"C\" Circuit Intermittent");
        put("P0875", "Transmission Fluid Pressure Sensor/Switch \"D\" Circuit");
        put("P0876", "Transmission Fluid Pressure Sensor/Switch \"D\" Circuit Range/Performance");
        put("P0877", "Transmission Fluid Pressure Sensor/Switch \"D\" Circuit Low");
        put("P0878", "Transmission Fluid Pressure Sensor/Switch \"D\" Circuit High");
        put("P0879", "Transmission Fluid Pressure Sensor/Switch \"D\" Circuit Intermittent");
        put("P0880", "TCM Power Input Signal");
        put("P0881", "TCM Power Input Signal Range/Performance");
        put("P0882", "TCM Power Input Signal Low");
        put("P0883", "TCM Power Input Signal High");
        put("P0884", "TCM Power Input Signal Intermittent");
        put("P0885", "TCM Power Relay Control Circuit/Open");
        put("P0886", "TCM Power Relay Control Circuit Low");
        put("P0887", "TCM Power Relay Control Circuit High");
        put("P0888", "TCM Power Relay Sense Circuit");
        put("P0889", "TCM Power Relay Sense Circuit Range/Performance");
        put("P0890", "TCM Power Relay Sense Circuit Low");
        put("P0891", "TCM Power Relay Sense Circuit High");
        put("P0892", "TCM Power Relay Sense Circuit Intermittent");
        put("P0893", "Multiple Gears Engaged");
        put("P0894", "Transmission Component Slipping");
        put("P0895", "Shift Time Too Short");
        put("P0896", "Shift Time Too Long");
        put("P0897", "Transmission Fluid Deteriorated");
        put("P0898", "Transmission Control System MIL Request Circuit Low");
        put("P0899", "Transmission Control System MIL Request Circuit High");
    }};

    /**
     * Body trouble codes
     */
    public static final Map<String, String> B = new HashMap<String, String>() {{

    }};

    /**
     * Chassis trouble codes
     */
    public static final Map<String, String> C = new HashMap<String, String>() {{

    }};

    /**
     * Network trouble codes
     */
    public static final Map<String, String> U = new HashMap<String, String>() {{

    }};
}